[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SGP30 Sensor@^1.1.10
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit SSD1306@^2.5.13
    adafruit/Adafruit GFX Library@^1.11.11
    dhtnew@^1.1.0
    bblanchon/ArduinoJson@^7.0.0
    wires/WiFiManager@^2.0.16
